### ISSUE TITLE
I want to know

### ISSUE THREAD

**Issue by andimdev** [dynocripto/DynoDev---Landing-Page#1]
¿qué pasó con la LP? :v

**Comment by dynocripto** [comment]
Este es un mensaje automático del equipo de Google. Lamentamos informar que
el destinatario no ha recibido el correo. Favor intente enviarlo nuevamente
en unas horas y, de presentar el mismo error, comuníquese con nosotros.
Este es un mensaje automático, por favor no responder al mismo.

**Comment by andimdev** [comment]
Este HP >:(

**Comment by andimdev** [comment]
¿qué ha hecho?
¿no hay nada nuevo?
